### ISSUE TITLE
`Chunk` func

### ISSUE THREAD

**Issue by qianxi0410** [rakeeb-hossain/functools#1]
Chunk consumes a slice of a generic type and returns a slice composed of multiple chunks of a user-specified size

Vacuously, empty slices return empty regardless of the chunk size.

When the chunk size is zero or negative, return an empty slice

exp:
```go
slice := []int{1, 2, 3, 4}
chunk := Chunk(slice, 2) // []int{{1,2}, {3, 4}}

chunk = Chunk(slice, 3) // []int{{1, 2, 3}, {4}}

chunk = Chunk(slice, 10) // []int{{1, 2, 3, 4}}

chunk = Chunk(slice, 0) // []int{}
```

**Comment by rakeeb-hossain** [comment]
I appreciate the interest, @qianxi0410 ! I actually quite like this function and can see it being useful for parallelizing jobs into "chunks". I can currently approve of the spec that you outlined. Did you want to go ahead and fork/implement this yourself?

**Comment by qianxi0410** [comment]
@rakeeb-hossain Thanks, I will submit a pr later :D
