### ISSUE TITLE
Filter: redundant memory allocation

### ISSUE THREAD

**Issue by crayoned** [rakeeb-hossain/functools#5]
You should not allocate new slice, it can be too expensive, just reuse old one
```
func Filter[T any](slice []T, predicate func(T) bool) []T {
	res := slice[:0]
	for _, v := range slice {
		if predicate(v) {
			res = append(res, v)
		}
	}
	return res
}
```

**Comment by rakeeb-hossain** [comment]
Hey @crayoned ! I believe this somewhat defeats the purpose of the "functional" nature of `Filter` - it should not mutate its arguments. 

That being said, I think this could be useful to have as a separate method. Potentially, a `FilterInPlace` that operates as you suggested. What do you think?

**Comment by crayoned** [comment]
Yes, you are right, filter should not mutate input data, I did not think about it. 
The idea to add FilterInPlace sounds great
